{{ if .Values.networkPolicies.enabled }}
# Allow egress to cluster for kube-api and kube-dns
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-to-cluster
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress: 
  - {}
{{- end }}