{{- if (and .Values.istio.enabled .Values.istio.mtls) -}}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: default
  namespace: eck-operator
spec:
  mtls:
    mode: STRICT
{{- end }}